version: '2'
services:
  neomodel:
    restart: always
    build: .
    environment:
      DATABASE_URL: db
    ports:
      - "5000:5000"
    volumes:
     - .:/code
    depends_on:
      - db
  db:
     image: neo4j:3.3
     environment:
       NEO4J_AUTH: none
     ports:
       - "7687:7687"
       - "7474:7474"
